homework_first_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: HomeworkFirstBundle:Default:index }

get_sitmap:
    pattern:  /sitmap
    defaults: { _controller: HomeworkFirstBundle:First:index }

