parameters:
#    homework_first.example.class: Homework\FirstBundle\Example

services:
#    homework_first.example:
#        class: %homework_first.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
